// LOCALHOST
### Get all users
GET http://localhost:3000/users


### Get contact by id
GET http://localhost:3000/users/622023f642f9ab4cd6e060b3


### Create contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName":"Ashley",
    "lastName":"Weaver",
    "email":"aWeaver@test.com",
    "favoriteColor":"Brown",
    "birthday":"06/19/2000"
}


### PUT contact
PUT http://localhost:3000/users/6220bcb39cd507e920c75a0b HTTP/1.1
content-type: application/json

{
    "firstName":"Sarah",
    "lastName":"Birch",
    "email":"test@gmail.com",
    "favoriteColor":"Green",
    "birthday":"12/12/20"
}
### DELETE contact
DELETE http://localhost:3000/users/6220b775099269ff7b31ceab HTTP/1.1